# Generated by Django 3.2.7 on 2021-09-29 22:50

from django.db import migrations, models
import djongo.models.fields
import pekerti.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('permission', djongo.models.fields.EmbeddedField(model_container=pekerti.models.Permission)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('validate_data', models.BooleanField()),
                ('update_data_peserta', models.BooleanField()),
                ('add_other_user', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nomer_telp', models.CharField(max_length=50)),
                ('link_transfer', models.CharField(max_length=50)),
                ('link_penugasan', models.CharField(max_length=50)),
                ('link_tidak_menggugat', models.CharField(max_length=50)),
                ('permission', djongo.models.fields.EmbeddedField(model_container=pekerti.models.Peserta_data)),
            ],
        ),
        migrations.CreateModel(
            name='Peserta_data',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('linkOpenLearning', models.CharField(max_length=50)),
                ('linkAksesKelas', models.CharField(max_length=50)),
                ('linkSertifikat', models.CharField(max_length=50)),
            ],
        ),
    ]
